# Generated by Django 3.1.7 on 2022-02-19 19:57

import apps.tesis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre de la tesis')),
                ('lugar', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre de la institución')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Resumen de la tesis')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract de la tesis')),
                ('imagen', models.FileField(blank=True, null=True, upload_to=apps.tesis.models.upload_to_tesis)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documents/pdf/')),
                ('link_tesis', models.URLField(blank=True, null=True, verbose_name='Url en donde se encuentra la tesis')),
                ('asignada', models.BooleanField(default=False, verbose_name='Asignación tesis')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
