# Generated by Django 2.2.26 on 2022-02-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de contacto'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='responsable',
            field=models.TextField(blank=True, null=True, verbose_name='Responsable'),
        ),
    ]
