# Generated by Django 4.2.14 on 2024-07-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0002_auto_20220221_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
