# Generated by Django 3.1.7 on 2022-02-19 19:57

import apps.lineas_investigacion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigadores', '0001_initial'),
        ('posgrados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineasInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre linea de investigación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción linea de investigación')),
                ('imagen_lin', models.FileField(upload_to=apps.lineas_investigacion.models.upload_to)),
                ('docentes', models.ManyToManyField(to='investigadores.Docentes')),
                ('posgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
