# Generated by Django 3.1.7 on 2022-02-19 19:57

import apps.investigadores.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('grado', models.CharField(blank=True, choices=[('Dr', 'Doctor'), ('Dra', 'Doctora'), ('MC', 'Maestro en Ciencias')], max_length=5, null=True, verbose_name='Grado')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del investigador')),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos del investigador')),
                ('formacion_profesional', models.CharField(blank=True, max_length=200, null=True, verbose_name='Formación profesional')),
                ('expertise', models.CharField(blank=True, max_length=200, null=True, verbose_name='Expertise')),
                ('sni', models.CharField(blank=True, choices=[('C', 'Candidato'), ('I', 'Nivel I'), ('II', 'Nivel II'), ('III', 'Nivel III')], max_length=5, null=True, verbose_name='SNI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del investigador')),
                ('perfil_researchgate', models.URLField(blank=True, null=True, verbose_name='Perfil Researchgate')),
                ('scholar_google', models.URLField(blank=True, null=True, verbose_name='Perfil Scholar Google')),
                ('personal_page', models.URLField(blank=True, null=True, verbose_name='Pagina Personal')),
                ('fotografia', models.FileField(blank=True, null=True, upload_to=apps.investigadores.models.upload_to_docentes)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del estudiante')),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos del estudiante')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo del estudiante')),
                ('revisor_externo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Revisor externo de tesis')),
                ('perfil_researchgate', models.URLField(blank=True, null=True, verbose_name='Perfil Researchgate')),
                ('scholar_google', models.URLField(blank=True, null=True, verbose_name='Perfil Scholar Google')),
                ('fotografia', models.FileField(blank=True, null=True, upload_to=apps.investigadores.models.upload_to_estudiantes)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_examen_grado', models.DateField(blank=True, null=True, verbose_name='Fecha de examen de grado')),
                ('actividad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Actividad del estudiante')),
                ('actividad_actual', models.CharField(blank=True, max_length=200, null=True, verbose_name='Actividad actual del estudiante')),
                ('nombre_institucion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la institución donde labora')),
                ('numero_acta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero de acta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la generación')),
                ('mes', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mes de inicio de la generación')),
                ('ano', models.CharField(blank=True, max_length=150, null=True, verbose_name='Año de la generación')),
                ('cohorte', models.FileField(blank=True, null=True, upload_to=apps.investigadores.models.upload_to_cohorte, verbose_name='Imagen de Cohorte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TiempoCompleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(default='Tiempo Completo', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutoriasManytoMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('docente', models.ManyToManyField(blank=True, to='investigadores.Docentes')),
                ('estudiante', models.ManyToManyField(blank=True, to='investigadores.Estudiantes')),
                ('generacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.generacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.docentes')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.estudiantes')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.generacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TiempoParcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, default='Tiempo Parcial', max_length=100, null=True)),
                ('docentes', models.ManyToManyField(blank=True, to='investigadores.Docentes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
