# Generated by Django 3.1.7 on 2022-02-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas_investigacion', '0001_initial'),
        ('investigadores', '0001_initial'),
        ('tesis', '0001_initial'),
        ('posgrados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempoparcial',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineas_investigacion.lineasinvestigacion'),
        ),
        migrations.AddField(
            model_name='tiempoparcial',
            name='posgrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados'),
        ),
        migrations.AddField(
            model_name='tiempocompleto',
            name='docentes',
            field=models.ManyToManyField(blank=True, to='investigadores.Docentes'),
        ),
        migrations.AddField(
            model_name='tiempocompleto',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineas_investigacion.lineasinvestigacion'),
        ),
        migrations.AddField(
            model_name='tiempocompleto',
            name='posgrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados'),
        ),
        migrations.AddField(
            model_name='generacion',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='investigadores.Estudiantes'),
        ),
        migrations.AddField(
            model_name='generacion',
            name='posgrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='codirector_tesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codirector_tesis', to='investigadores.docentes'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='director_tesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_tesis', to='investigadores.docentes'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='posgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='revisores_tesis',
            field=models.ManyToManyField(blank=True, to='investigadores.Docentes'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='tesis_estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tesis.tesis'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='posgrado',
            field=models.ManyToManyField(blank=True, to='posgrados.Posgrados'),
        ),
    ]
