# Generated by Django 3.1.7 on 2022-02-19 19:57

import apps.slides.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posgrados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la imagen que tendrá en el carrousel')),
                ('imagen', models.FileField(upload_to=apps.slides.models.upload_to_slides)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('posgrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
