# Generated by Django 3.1.7 on 2022-02-19 19:57

import apps.posgrados.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posgrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del posgrado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del posgrado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del laboratorio')),
                ('imagen', models.FileField(blank=True, null=True, upload_to=apps.posgrados.models.laboratorio)),
                ('imagen_2', models.FileField(blank=True, null=True, upload_to=apps.posgrados.models.laboratorio)),
                ('imagen_3', models.FileField(blank=True, null=True, upload_to=apps.posgrados.models.laboratorio)),
                ('imagen_descripcion', models.FileField(blank=True, null=True, upload_to=apps.posgrados.models.laboratorio)),
                ('descripcion_breve', models.TextField(blank=True, null=True, verbose_name='Descripción corta')),
                ('descripcion_1', models.TextField(blank=True, null=True, verbose_name='Descripción parte 1')),
                ('descripcion_2', models.TextField(blank=True, null=True, verbose_name='Descripción parte 2')),
                ('posgrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
