# Generated by Django 3.1.7 on 2022-02-19 19:57

import apps.colaboraciones.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posgrados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del imagen')),
                ('imagen', models.FileField(blank=True, null=True, upload_to=apps.colaboraciones.models.galeria)),
                ('posgrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Colaboraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('nombre_institucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del la institución')),
                ('imagen_institucion', models.FileField(blank=True, null=True, upload_to=apps.colaboraciones.models.upload_to)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('posgrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgrados.posgrados')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
